#!/bin/bash

LEDGER_ECOSYSTEM_DIR=/home/alex/money/scripts

export LEDGER_FILE=/home/alex/money/money.ledger
export LEDGER_PRICE_DB=/home/alex/money/ledger.pricedb

l () {
ledger -f ${LEDGER_FILE} --price-db ${LEDGER_PRICE_DB} -V --pager less --date-format='%d-%b-%y' $*
}


# These variables are used for reports/csv imports
# Useful for automation

THIS_MTH=$(date +'%b' | tr '[:upper:]' '[:lower:]') # Abbreviated Month Name, ex: "apr"
LAST_MTH=$(date +'%b' -d 'last month' | tr '[:upper:]' '[:lower:]') # "apr"
THIS_YEAR=$(date +'%Y') # "2016"
LAST_YEAR=$(date +'%Y' -d 'last year') # "2015"
LAST_MTH_AND_YEAR="${LAST_AMN}${THIS_YEAR}" # "apr2015"
if [[ "$LAST_MTH" == "dec" ]]; then
    LAST_MTH_AND_YEAR="${LAST_MTH}${LAST_YEAR}"
fi



# Ledger tmux
alias slt='tmuxinator start ledger'


# This is where CSV files are stored.
CSV_DIR=./csv
