#! /bin/sh

bspc config border_width        2
bspc config window_gap          30

bspc config top_padding    0
bspc config right_padding  0
bspc config bottom_padding 0
bspc config left_padding   0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d "α" "β" "γ" "δ" "ε" "ζ"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Autostart

xsetroot -cursor_name left_ptr
/home/alex/.config/bar/panel &
